#!/usr/bin/env python3

import argparse

modules = {
    'backend': {},
    'frontend': {},
}


def parse_args():
    parser = argparse.ArgumentParser(description='generates new dockerfiles for selected modules')

    available_modules = sorted(modules.keys())

    parser.add_argument(
        '--modules',
        nargs='*', default=available_modules, choices=available_modules,
        help='Module(s) that should built (both by default)'
    )

    available_modes = ['production', 'development']

    parser.add_argument(
        '--mode',
        choices=available_modes, default='production',
        help='Mode to build modules'
    )

    parser.add_argument(
        '-o', '--output',
        type=str,
        help='Directory to output generated dockerfiles'
    )

    parser.add_argument(
        '-b', '--build',
        action='store_true',
        help='Build images by generated dockerfile(s)',
    )

    parser.add_argument(
        '-D', '--debug',
        action='store_true',
        help='Makes application to output debugging information',
    )

    parser.add_argument(
        '-d', '--dry-run',
        action='store_true',
        help='Run app without making changes',
    )

    result = parser.parse_args()
    result.modules = sorted(set(result.modules)) if result.modules else available_modules
    return result


args = parse_args()
print(args)

# TODO: generate dockerfile(s)

# TODO: build awesome containers!
