#!/usr/bin/env python3

import argparse

modules = {
    'backend': {},
    'frontend': {},
}


def parse_args():
    parser = argparse.ArgumentParser(description='generates new dockerfiles for selected modules')

    available_modules = sorted(modules.keys())

    parser.add_argument(
        '--modules', help='Module(s) that should built (both by default)',
        nargs='*', choices=available_modules,
    )

    available_modes = ['production', 'development']

    parser.add_argument(
        '--mode', help='Mode to build modules',
        choices=available_modes, default='production',
    )

    parser.add_argument(
        '-o', '--output', help='Directory to output generated dockerfiles',
        type=str,
    )

    parser.add_argument(
        '-b', '--build', help='Build images by generated dockerfile(s)',
        action='store_true',
    )

    parser.add_argument(
        '-D', '--debug', help='Makes application to output debugging information',
        action='store_true',
    )

    parser.add_argument(
        '-d', '--dry-run', help='Run app without making changes',
        action='store_true',
    )

    result = parser.parse_args()
    result.modules = sorted(set(result.modules)) if result.modules else available_modules
    return result


args = parse_args()
print(args)

# TODO: generate dockerfile(s)

# TODO: build awesome containers!
